# Generated by Django 3.2 on 2025-11-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0002_add_location_to_destination_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationpackagemapping',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaddestinationmapping',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadpackage',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
