# Generated by Django 3.0.7 on 2024-10-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0003_auto_20241016_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroperator',
            name='renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
