# Generated by Django 3.2 on 2025-11-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0004_add_itinerary_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='image_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
