# Generated by Django 3.0.7 on 2024-10-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0004_auto_20241016_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('user', 'User')], default='user', max_length=50, null=True),
        ),
    ]
