# Generated by Django 3.2 on 2025-11-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0007_simplify_transaction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='package_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.destination'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_management.lead'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='package_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tour_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_management.touroperator'),
        ),
    ]
