# Generated by Django 3.0.7 on 2024-10-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0007_auto_20241016_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='phoneno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
