# Generated by Django 3.0.7 on 2024-10-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0008_hotel_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, choices=[('studio', 'Studio'), ('standard', 'Standard'), ('delux', 'Delux'), ('suite', 'Suite'), ('superior', 'Superior'), ('superior', 'Superior'), ('family', 'Family'), ('executive', 'Executive'), ('villa', 'Villa')], default='standard', max_length=100, null=True),
        ),
    ]
