# Generated by Django 3.2 on 2025-11-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0009_add_company_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='module',
            field=models.CharField(choices=[('destination', 'Destination'), ('package', 'Package'), ('hotel', 'Hotel'), ('room', 'Room'), ('car_dealer', 'Car Dealer'), ('event', 'Event'), ('sightseeing', 'Sightseeing'), ('itinerary_item', 'Itinerary Item'), ('company_profile', 'Company Profile')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together={('tour_operator_id', 'name')},
        ),
        migrations.AlterModelTable(
            name='touroperatorquota',
            table='tour_management_touroperatorquota',
        ),
    ]
