# Generated by Django 3.0.7 on 2024-10-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0010_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardealer',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='cardealer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
