# Generated by Django 3.2 on 2025-11-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0010_add_destination_unique_constraint'),
    ]

    operations = [
        migrations.RunSQL(
            # Create unique index with prefix lengths to stay within MySQL key length limit
            # Using prefix lengths: name(100), city(100), state(50), country(50)
            # Total: 8 (FK) + 400 + 400 + 200 + 200 = 1208 bytes (well under 3072 limit)
            sql="""
                CREATE UNIQUE INDEX Location_tour_operator_id_name_city_state_country_uniq
                ON Location (tour_operator_id, name(100), city(100), state(50), country(50))
            """,
            reverse_sql="""
                DROP INDEX Location_tour_operator_id_name_city_state_country_uniq ON Location
            """
        ),
    ]
