# Generated by Django 3.2 on 2025-11-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0011_add_location_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.user')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tour_management.package')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.touroperator')),
            ],
            options={
                'db_table': 'PackageOption',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PackageOptionHotelMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.hotel')),
                ('package_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_mappings', to='tour_management.packageoption')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.user')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.touroperator')),
            ],
            options={
                'db_table': 'PackageOptionHotelMapping',
                'ordering': ['day', 'id'],
            },
        ),
    ]
