# Generated by Django 3.2 on 2025-11-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0012_packageoption_packageoptionhotelmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPackageOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.user')),
                ('lead_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_options', to='tour_management.leadpackage')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.touroperator')),
            ],
            options={
                'db_table': 'LeadPackageOption',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='selected_package_option_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selected_package_option_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LeadPackageOptionHotelMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_management.hotel')),
                ('lead_package_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_mappings', to='tour_management.leadpackageoption')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.user')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.touroperator')),
            ],
            options={
                'db_table': 'LeadPackageOptionHotelMapping',
                'ordering': ['day', 'id'],
            },
        ),
    ]
