# Generated by Django 3.0.7 on 2024-10-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0012_cartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='car_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Cardealer'),
        ),
    ]
