# Generated by Django 3.2 on 2025-11-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0013_auto_20251125_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpackageoptionhotelmapping',
            name='quick_hotel_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionitineraryitem',
            name='quick_hotel_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadpackageoptionhotelmapping',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.hotel'),
        ),
        migrations.AlterField(
            model_name='packageoptionhotelmapping',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.hotel'),
        ),
        migrations.CreateModel(
            name='QuickHotel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('studio', 'Studio'), ('standard', 'Standard'), ('delux', 'Delux'), ('suite', 'Suite'), ('superior', 'Superior'), ('superior', 'Superior'), ('family', 'Family'), ('executive', 'Executive'), ('villa', 'Villa')], max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rooms', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.user')),
                ('tour_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.touroperator')),
            ],
            options={
                'db_table': 'QuickHotel',
            },
        ),
        migrations.AddField(
            model_name='packageoptionhotelmapping',
            name='quick_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.quickhotel'),
        ),
    ]
