# Generated by Django 3.0.7 on 2024-10-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0013_cartype_car_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardealer',
            name='car_types',
        ),
    ]
