# Generated by Django 3.2 on 2025-11-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0014_add_quick_hotel_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOptionCarDealerMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.cardealer')),
                ('package_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_mappings', to='tour_management.packageoption')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.user')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.touroperator')),
            ],
            options={
                'db_table': 'PackageOptionCarDealerMapping',
                'ordering': ['day', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadPackageOptionCarDealerMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_management.cardealer')),
                ('lead_package_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_mappings', to='tour_management.leadpackageoption')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.user')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.touroperator')),
            ],
            options={
                'db_table': 'LeadPackageOptionCarDealerMapping',
                'ordering': ['day', 'id'],
            },
        ),
    ]
