# Generated by Django 3.0.7 on 2024-10-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0014_remove_cardealer_car_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
