# Generated by Django 3.0.7 on 2024-10-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0015_cartype_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='no_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
