# Generated by Django 3.2 on 2025-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0016_add_vehicle_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='travel_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='travel_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
