# Generated by Django 3.0.7 on 2024-10-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0016_auto_20241019_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Destination'),
        ),
    ]
