# Generated by Django 3.0.7 on 2024-10-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0017_event_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('room', 'Room'), ('event', 'Event'), ('cardealer', 'CarDealer')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, choices=[('hotel', 'Hotel'), ('room', 'Room'), ('event', 'Event'), ('cardealer', 'CarDealer')], null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.User')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Touroperator')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('room', 'Room'), ('event', 'Event'), ('cardealer', 'CarDealer')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, choices=[('hotel', 'Hotel'), ('room', 'Room'), ('event', 'Event'), ('cardealer', 'CarDealer')], null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.User')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Touroperator')),
            ],
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('room', 'Room'), ('event', 'Event'), ('cardealer', 'CarDealer')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, choices=[('hotel', 'Hotel'), ('room', 'Room'), ('event', 'Event'), ('cardealer', 'CarDealer')], null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.User')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Touroperator')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, choices=[('hotel', 'Hotel'), ('room', 'Room'), ('event', 'Event'), ('cardealer', 'CarDealer')], null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.User')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Touroperator')),
            ],
            options={
                'db_table': 'ContactInfo',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('room', 'Room'), ('event', 'Event'), ('cardealer', 'CarDealer')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, choices=[('hotel', 'Hotel'), ('room', 'Room'), ('event', 'Event'), ('cardealer', 'CarDealer')], null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.User')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Touroperator')),
            ],
        ),
    ]
