# Generated by Django 3.2 on 2025-11-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0017_auto_20251127_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpackageoptionhotelmapping',
            name='room_quantity',
            field=models.IntegerField(blank=True, help_text='Number of rooms required', null=True),
        ),
        migrations.AddField(
            model_name='leadpackageoptionhotelmapping',
            name='room_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadpackageoptionhotelmapping',
            name='selected_room_type',
            field=models.ForeignKey(blank=True, help_text='Selected room type from the hotel (snapshot reference)', null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.room'),
        ),
        migrations.AddField(
            model_name='packageoptionhotelmapping',
            name='room_quantity',
            field=models.IntegerField(blank=True, help_text='Number of rooms required', null=True),
        ),
        migrations.AddField(
            model_name='packageoptionhotelmapping',
            name='selected_room_type',
            field=models.ForeignKey(blank=True, help_text='Selected room type from the hotel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour_management.room'),
        ),
        migrations.AddField(
            model_name='transactionitineraryitem',
            name='room_quantity',
            field=models.IntegerField(blank=True, help_text='Number of rooms booked', null=True),
        ),
        migrations.AddField(
            model_name='transactionitineraryitem',
            name='room_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionitineraryitem',
            name='selected_room_type',
            field=models.ForeignKey(blank=True, help_text='Selected room type from the hotel (snapshot reference)', null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.room'),
        ),
    ]
