# Generated by Django 3.0.7 on 2024-10-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0018_amenity_contactinfo_exclusion_inclusion_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
