# Generated by Django 3.2 on 2025-12-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0019_add_package_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='meal_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quickhotel',
            name='meal_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
