# Generated by Django 3.0.7 on 2024-10-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0020_auto_20241027_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statecitytodestinationmapping',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.Destination'),
        ),
        migrations.AlterField(
            model_name='statecitytodestinationmapping',
            name='state_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour_management.StateCity'),
            preserve_default=False,
        ),
    ]
