# Generated by Django 3.0.7 on 2024-10-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0021_auto_20241027_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='destination',
        ),
        migrations.CreateModel(
            name='SightSeeing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.User')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Location')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Touroperator')),
            ],
            options={
                'db_table': 'SightSeeing',
            },
        ),
    ]
