# Generated by Django 3.0.7 on 2024-10-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0022_auto_20241027_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('couple', 'Couple'), ('honeymoon', 'Honeymoon'), ('group', 'Group')], max_length=100, null=True),
        ),
    ]
