# Generated by Django 3.2 on 2025-12-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0022_auto_20251212_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='exclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='inclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadpackage',
            name='package_exclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadpackage',
            name='package_inclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='package_exclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='package_inclusions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
