# Generated by Django 3.0.7 on 2024-10-29 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0023_auto_20241029_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationPackageMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destination_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Destination')),
                ('package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Package')),
                ('tour_operator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Touroperator')),
            ],
            options={
                'db_table': 'DestinationPackageMapping',
            },
        ),
    ]
