# Generated by Django 3.2 on 2025-12-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0023_auto_20251224_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='record_id',
            field=models.CharField(max_length=255),
        ),
    ]
