# Generated by Django 3.2 on 2025-12-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0024_alter_imagemetadata_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealer',
            name='image_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightseeing',
            name='image_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
