# Generated by Django 3.0.7 on 2024-10-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0024_destinationpackagemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationpackagemapping',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destinationpackagemapping',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationpackagemapping',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
