# Generated by Django 3.0.7 on 2024-10-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0025_auto_20241029_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description',
            new_name='address',
        ),
    ]
