# Generated by Django 3.0.7 on 2024-10-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0026_auto_20241030_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bedtype',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('twin', 'Twin'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('bunk', 'Bunk'), ('rollaway', 'Rollaway'), ('trundle', 'Trundle'), ('daybed', 'Daybed')], default='standard', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
