# Generated by Django 3.0.7 on 2024-10-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0027_auto_20241030_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bedtype',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('twin', 'Twin'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('bunk', 'Bunk'), ('rollaway', 'Rollaway'), ('trundle', 'Trundle'), ('daybed', 'Daybed')], max_length=100, null=True),
        ),
    ]
