# Generated by Django 3.0.7 on 2024-10-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0028_auto_20241030_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country_code',
            new_name='pin_code',
        ),
    ]
