# Generated by Django 3.0.7 on 2024-10-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0029_auto_20241031_0806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('tour_operator', 'name', 'city', 'country')},
        ),
    ]
