# Generated by Django 3.0.7 on 2024-11-01 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0031_hotel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHotelMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.Hotel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.Package')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.User')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Touroperator')),
            ],
            options={
                'db_table': 'PackageHotelMapping',
                'unique_together': {('package', 'hotel', 'tour_operator')},
            },
        ),
        migrations.CreateModel(
            name='PackageCarDealerMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.Cardealer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.Package')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.User')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.Touroperator')),
            ],
            options={
                'db_table': 'PackageCarDealerMapping',
                'unique_together': {('package', 'car_dealer', 'tour_operator')},
            },
        ),
    ]
