# Generated by Django 3.0.7 on 2024-11-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0032_packagecardealermapping_packagehotelmapping'),
    ]

    operations = [
       # migrations.AlterUniqueTogether(
       #     name='location',
       #     unique_together={('tour_operator', 'name', 'address', 'city', 'country')},
       # ),
    ]
