# Generated by Django 3.0.7 on 2024-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0033_auto_20241101_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
