# Generated by Django 3.0.7 on 2024-11-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0034_auto_20241101_1203'),
    ]

    operations = [
        #migrations.AlterUniqueTogether(
        #    name='location',
        #    unique_together=set(),
        #),
    ]
