# Generated by Django 3.0.7 on 2024-11-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0035_auto_20241101_1205'),
    ]

    operations = [
        
    ]
