# Generated by Django 3.0.7 on 2024-11-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0039_auto_20241101_1227'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='location',
        #    name='address',
        #    field=models.TextField(blank=True, db_index=True, null=True),
        #),
    ]
