# Generated by Django 3.0.7 on 2024-11-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0040_auto_20241101_1228'),
    ]

    operations = [
       # migrations.AlterField(
       #     model_name='location',
       #     name='address',
       #     field=models.TextField(blank=True, null=True),
       # ),
       # migrations.AlterUniqueTogether(
       #     name='location',
       #     unique_together=set(),
       # ),
    ]
