# Generated by Django 3.0.7 on 2024-11-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0041_auto_20241101_1229'),
    ]

    operations = [
    #    migrations.AlterField(
    #        model_name='location',
    #        name='address',
    #        field=models.TextField(blank=True, max_length=1024, null=True),
    #    ),
    #    migrations.AlterUniqueTogether(
    #        name='location',
    #        unique_together={('tour_operator', 'name', 'city', 'country')},
    #    ),
    ]
