# Generated by Django 3.0.7 on 2024-11-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0042_auto_20241101_1230'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
