# Generated by Django 3.0.7 on 2024-11-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0043_auto_20241101_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecardealermapping',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagehotelmapping',
            name='day',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
