# Generated by Django 3.0.7 on 2024-11-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0044_auto_20241101_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitinerary',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transactionitinerary',
            name='event',
        ),
        migrations.RemoveField(
            model_name='transactionitinerary',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='transactionitinerary',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='transactionitinerary',
            name='tour_operator',
        ),
        migrations.RemoveField(
            model_name='transactionitinerary',
            name='transaction',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionItinerary',
        ),
    ]
