# Generated by Django 3.2 on 2024-11-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0045_auto_20241102_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('package_type', models.CharField(max_length=100)),
                ('pax_size', models.IntegerField(blank=True, null=True)),
                ('contains_travel_fare', models.BooleanField(default=False)),
                ('transport_type', models.CharField(blank=True, max_length=45, null=True)),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('package_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('proposed_package_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('original_package_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('margin_of_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('package_amenities', models.JSONField(blank=True, null=True)),
                ('package_inclusions', models.JSONField(blank=True, null=True)),
                ('package_exclusions', models.JSONField(blank=True, null=True)),
                ('package_policies', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_management.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_management.customer')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_management.destination')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_management.package')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.touroperator')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionDayDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('hotel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_description', models.TextField(blank=True, null=True)),
                ('hotel_ratings', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('hotel_phoneno', models.CharField(blank=True, max_length=15, null=True)),
                ('hotel_website', models.URLField(blank=True, null=True)),
                ('hotel_location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_location_state', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_location_country', models.CharField(blank=True, max_length=255, null=True)),
                ('car_dealer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('car_dealer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('car_dealer_location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('car_dealer_location_state', models.CharField(blank=True, max_length=255, null=True)),
                ('car_dealer_location_country', models.CharField(blank=True, max_length=255, null=True)),
                ('car_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('car_type_capacity', models.IntegerField(blank=True, null=True)),
                ('hotel_amenities', models.JSONField(blank=True, null=True)),
                ('hotel_inclusions', models.JSONField(blank=True, null=True)),
                ('hotel_exclusions', models.JSONField(blank=True, null=True)),
                ('hotel_policies', models.JSONField(blank=True, null=True)),
                ('car_dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.cardealer')),
                ('car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.cartype')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.hotel')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_details', to='tour_management.transaction')),
            ],
            options={
                'db_table': 'TransactionDayDetails',
                'unique_together': {('transaction', 'day')},
            },
        ),
        migrations.CreateModel(
            name='TransactionRoomDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('room_type', models.CharField(blank=True, max_length=100, null=True)),
                ('room_capacity', models.IntegerField(blank=True, null=True)),
                ('room_bedtype', models.CharField(blank=True, max_length=100, null=True)),
                ('room_price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('inclusions', models.JSONField(blank=True, null=True)),
                ('exclusions', models.JSONField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.room')),
                ('transaction_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_details', to='tour_management.transactiondaydetails')),
            ],
            options={
                'db_table': 'TransactionRoomDetails',
            },
        ),
        migrations.CreateModel(
            name='TransactionItineraryDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('event', 'Event'), ('sightseeing', 'Sightseeing')], max_length=50)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('location_state', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('location_country', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itinerary_details', to='tour_management.transactiondaydetails')),
            ],
            options={
                'db_table': 'TransactionItineraryDetails',
            },
        ),
    ]
