# Generated by Django 3.2 on 2024-11-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0046_transaction_transactiondaydetails_transactionitinerarydetails_transactionroomdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondaydetails',
            name='hotel_location_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='hotel_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.location'),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='hotel_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionitinerarydetails',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.location'),
        ),
    ]
