# Generated by Django 3.2 on 2024-11-02 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0047_auto_20241102_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondaydetails',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.room'),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='room_amenities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='room_bedtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='room_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='room_exclusions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='room_inclusions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='room_policies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='room_price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactiondaydetails',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TransactionRoomDetails',
        ),
    ]
