# Generated by Django 3.2 on 2024-11-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0048_auto_20241102_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tour_operator_id',
            new_name='tour_operator',
        ),
    ]
