# Generated by Django 3.2 on 2024-11-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0049_rename_tour_operator_id_customer_tour_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('followup', 'Follow-up'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.customer')),
            ],
            options={
                'db_table': 'Lead',
            },
        ),
        migrations.CreateModel(
            name='LeadPackage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('family', 'Family'), ('couple', 'Couple'), ('honeymoon', 'Honeymoon'), ('group', 'Group')], max_length=100, null=True)),
                ('pax_size', models.IntegerField(blank=True, null=True)),
                ('contains_travel_fare', models.BooleanField(default=False)),
                ('transport_type', models.CharField(blank=True, max_length=45, null=True)),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('package_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.destination')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.lead')),
                ('tour_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.touroperator')),
            ],
            options={
                'db_table': 'LeadPackage',
            },
        ),
        migrations.CreateModel(
            name='LeadItineraryItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.itineraryitem')),
                ('lead_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.leadpackage')),
            ],
            options={
                'db_table': 'LeadItineraryItem',
            },
        ),
        migrations.CreateModel(
            name='LeadHotelMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.hotel')),
                ('lead_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.leadpackage')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.user')),
            ],
            options={
                'db_table': 'LeadHotelMapping',
            },
        ),
        migrations.CreateModel(
            name='LeadDestinationMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.destination')),
                ('lead_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.leadpackage')),
            ],
            options={
                'db_table': 'LeadDestinationMapping',
            },
        ),
        migrations.CreateModel(
            name='LeadCarDealerMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.cardealer')),
                ('lead_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.leadpackage')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_management.user')),
            ],
            options={
                'db_table': 'LeadCarDealerMapping',
            },
        ),
    ]
