# Generated by Django 3.2 on 2024-11-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0053_leaddestinationmapping_tour_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcardealermapping',
            name='tour_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.touroperator'),
        ),
        migrations.AddField(
            model_name='leadhotelmapping',
            name='tour_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.touroperator'),
        ),
        migrations.AddField(
            model_name='leaditineraryitem',
            name='tour_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.touroperator'),
        ),
    ]
