# Generated by Django 3.2 on 2024-11-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0055_leaditineraryitem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaditineraryitem',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_management.destination'),
        ),
    ]
