# Generated by Django 3.2 on 2024-11-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0056_leaditineraryitem_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaditineraryitem',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaditineraryitem',
            name='item_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaditineraryitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaditineraryitem',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
