# Generated by Django 3.2 on 2024-11-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0057_auto_20241104_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaditineraryitem',
            name='city',
        ),
        migrations.RemoveField(
            model_name='leaditineraryitem',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='leaditineraryitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='leaditineraryitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='leaditineraryitem',
            name='state',
        ),
        migrations.RemoveField(
            model_name='leaditineraryitem',
            name='tour_operator',
        ),
    ]
