# Generated by Django 3.2 on 2024-11-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0058_auto_20241104_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('destination', 'Destination'), ('package', 'Package'), ('hotel', 'Hotel'), ('room', 'Room'), ('car_dealer', 'Car Dealer'), ('event', 'Event'), ('sightseeing', 'Sightseeing')], max_length=50)),
                ('record_id', models.BigIntegerField()),
                ('image_path', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_management.touroperator')),
            ],
            options={
                'db_table': 'ImageMetadata',
                'unique_together': {('tour_operator', 'module', 'record_id', 'order')},
            },
        ),
    ]
