# Generated by Django 3.2 on 2024-11-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0059_imagemetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourOperatorQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_images_destination', models.PositiveIntegerField(default=5)),
                ('max_images_package', models.PositiveIntegerField(default=3)),
                ('max_images_hotel', models.PositiveIntegerField(default=10)),
                ('max_images_room', models.PositiveIntegerField(default=10)),
                ('max_images_car_dealer', models.PositiveIntegerField(default=3)),
                ('max_images_event', models.PositiveIntegerField(default=3)),
                ('max_images_sightseeing', models.PositiveIntegerField(default=3)),
                ('tour_operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tour_management.touroperator')),
            ],
        ),
    ]
