# Generated by Django 3.2 on 2024-11-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0061_alter_imagemetadata_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationpackagemapping',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationpackagemapping',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
