# Generated by Django 3.2 on 2024-11-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0062_auto_20241111_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagehotelmapping',
            unique_together=set(),
        ),
    ]
