# Generated by Django 3.2 on 2024-11-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0063_alter_packagehotelmapping_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagecardealermapping',
            unique_together=set(),
        ),
    ]
