# Generated by Django 3.2 on 2024-11-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0065_auto_20241112_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
