# Generated by Django 3.2 on 2025-04-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tour_management', '0066_user_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='entity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='entity_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='parent_entity_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='parent_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='imagemetadata',
            index=models.Index(fields=['content_type', 'object_id'], name='ImageMetada_content_f6b56b_idx'),
        ),
    ]
