# Generated by Django 3.2 on 2025-04-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0068_populate_image_content_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='imagemetadata',
            name='ImageMetada_content_f6b56b_idx',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='object_id',
        ),
        migrations.AddField(
            model_name='cardealer',
            name='image_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='image_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='image_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='image_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
