# Generated by Django 3.2 on 2025-04-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_management', '0069_auto_20250416_1659'),
        ('tour_management', '0070_auto_20250416_1659'),
    ]

    operations = [
    ]
